2025-01-08 09:19:55,771 INFO    MainThread:8717 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-08 09:19:55,771 INFO    MainThread:8717 [wandb_setup.py:_flush():68] Configure stats pid to 8717
2025-01-08 09:19:55,771 INFO    MainThread:8717 [wandb_setup.py:_flush():68] Loading settings from /Users/paulnitschke/.config/wandb/settings
2025-01-08 09:19:55,771 INFO    MainThread:8717 [wandb_setup.py:_flush():68] Loading settings from /Users/paulnitschke/Desktop/projects/geo_meta_rl/wandb/settings
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_init.py:_log_setup():528] Logging user logs to /Users/paulnitschke/Desktop/projects/geo_meta_rl/wandb/run-20250108_091955-8qtqpv5d/logs/debug.log
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_init.py:_log_setup():529] Logging internal logs to /Users/paulnitschke/Desktop/projects/geo_meta_rl/wandb/run-20250108_091955-8qtqpv5d/logs/debug-internal.log
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_init.py:init():644] calling init triggers
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'seed': 1, 'num_epochs': 3, 'num_train_tasks': 2, 'num_test_tasks': 20, 'latent_size': 5, 'encoder_hidden_size': 256, 'net_size': 256, 'n_negative_samples': 12, 'meta_batch_size': 32, 'num_steps_per_epoch': 15, 'num_initial_steps': 1200, 'num_tasks_sample': 5, 'num_steps_prior': 500, 'num_extra_rl_steps_posterior': 400, 'batch_size': 256, 'embedding_batch_size': 64, 'embedding_mini_batch_size': 64, 'reward_scale': 10.0, 'max_episode_length': 200, 'use_gpu': False}
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_init.py:init():680] starting backend
2025-01-08 09:19:55,772 INFO    MainThread:8717 [wandb_init.py:init():684] sending inform_init request
2025-01-08 09:19:55,818 INFO    MainThread:8717 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-08 09:19:55,818 INFO    MainThread:8717 [wandb_init.py:init():697] backend started and connected
2025-01-08 09:19:55,823 INFO    MainThread:8717 [wandb_init.py:init():790] updated telemetry
2025-01-08 09:19:55,860 INFO    MainThread:8717 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-08 09:19:56,331 INFO    MainThread:8717 [wandb_init.py:init():874] starting run threads in backend
2025-01-08 09:19:56,488 INFO    MainThread:8717 [wandb_run.py:_console_start():2374] atexit reg
2025-01-08 09:19:56,488 INFO    MainThread:8717 [wandb_run.py:_redirect():2224] redirect: wrap_raw
2025-01-08 09:19:56,488 INFO    MainThread:8717 [wandb_run.py:_redirect():2289] Wrapping output streams.
2025-01-08 09:19:56,488 INFO    MainThread:8717 [wandb_run.py:_redirect():2314] Redirects installed.
2025-01-08 09:19:56,490 INFO    MainThread:8717 [wandb_init.py:init():916] run started, returning control to user process
2025-01-08 09:20:14,541 ERROR   MainThread:8717 [util.py:get_module():249] Error importing optional module torchvision.utils
Traceback (most recent call last):
  File "/Users/paulnitschke/miniconda3/envs/env_geo_meta_rl/lib/python3.9/site-packages/wandb/util.py", line 215, in import_module_lazy
    return sys.modules[name]
KeyError: 'torchvision.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paulnitschke/miniconda3/envs/env_geo_meta_rl/lib/python3.9/site-packages/wandb/util.py", line 244, in get_module
    return import_module_lazy(name)
  File "/Users/paulnitschke/miniconda3/envs/env_geo_meta_rl/lib/python3.9/site-packages/wandb/util.py", line 217, in import_module_lazy
    spec = importlib.util.find_spec(name)
  File "/Users/paulnitschke/miniconda3/envs/env_geo_meta_rl/lib/python3.9/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'torchvision'
2025-01-08 09:20:14,548 WARNING MsgRouterThr:8717 [router.py:message_loop():75] message_loop has been closed
